'use strict';
const width = 9;
const height = 5;
const area = width * height;
console.log('the value of area is:', area);
console.log('typeof area:', typeof area);
const bill = 35;
const payment = 50;
const change = payment - bill;
console.log('the value of change:', change);
console.log('typeof change:', typeof change);
const quizzes = 15;
const midterm = 4;
const final = 2;
const grade = (quizzes + midterm + final) / 3;
console.log('the value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Mark';
const lastName = 'Matlock';
const fullName = firstName + ' ' + lastName;
console.log('the value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log('the value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const headCount = 57;
const isSparta = headCount === 300;
console.log('the value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('the value of motto:', motto);
console.log('typeof motto:', typeof motto);
